# prefix key
set-option -g prefix C-t
bind t send-prefix
# japanese
set-window-option -g utf8 on
# scrole
set-window-option -g mode-mouse on
set-window-option -g mode-keys vi
# copy
set -g mode-mouse on
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on
# how to copy
bind / list-keys -t vi-copy
# resize pane
bind-key  J resize-pane -D
bind-key  K resize-pane -U
bind-key  L resize-pane -L
bind-key  H resize-pane -R