#!/usr/bin/env bash
set -euo pipefail

# Usage information
usage() {
    cat << EOF
Usage: $0 [FOLDER_NAME]

Retrieve secrets from a Bitwarden folder and restore them to the local system.

Arguments:
  FOLDER_NAME    Name of the Bitwarden folder containing secrets (default: "example")

Examples:
  $0                        # Use default folder "example"
  $0 "my-project"          # Use custom folder "my-project"

Environment Variables:
  BW_SESSION    Bitwarden session token (required)
                Get it with: export BW_SESSION=\$(bw unlock --raw)
EOF
    exit 1
}

# Parse arguments
if [ "${1:-}" == "-h" ] || [ "${1:-}" == "--help" ]; then
    usage
fi

FOLDER_NAME="${1:-example}"

echo "🔐 Retrieving secrets from Bitwarden..."

# Check if Bitwarden CLI is installed
if ! command -v bw &> /dev/null; then
    echo "❌ Bitwarden CLI (bw) is not installed."
    echo "Please install it first: nix profile install nixpkgs#bitwarden-cli"
    exit 1
fi

# Check if logged in and unlocked
if [ -z "${BW_SESSION:-}" ]; then
    echo "❌ BW_SESSION is not set."
    echo "Please login and unlock Bitwarden first:"
    echo ""
    echo "  bw login"
    echo "  export BW_SESSION=\$(bw unlock --raw)"
    echo ""
    exit 1
fi

# Get folder ID
FOLDER_ID=$(bw list folders --session "$BW_SESSION" | jq -r ".[] | select(.name == \"$FOLDER_NAME\") | .id")

if [ -z "$FOLDER_ID" ]; then
    echo "❌ Folder '$FOLDER_NAME' not found in Bitwarden."
    echo ""
    echo "Available folders:"
    bw list folders --session "$BW_SESSION" | jq -r '.[] | "  - \(.name)"'
    echo ""
    exit 1
fi

echo "📁 Using folder: $FOLDER_NAME (ID: $FOLDER_ID)"

# Helper function to safely get password from Bitwarden (from specific folder)
get_password() {
    local item_name="$1"
    bw list items --folderid "$FOLDER_ID" --session "$BW_SESSION" | \
        jq -r ".[] | select(.name == \"$item_name\") | .login.password // \"\""
}

# Helper function to safely get notes from Bitwarden (from specific folder)
get_notes() {
    local item_name="$1"
    bw list items --folderid "$FOLDER_ID" --session "$BW_SESSION" | \
        jq -r ".[] | select(.name == \"$item_name\") | .notes // \"\""
}

# Create necessary directories
mkdir -p ~/.ssh
mkdir -p ~/.aws

echo "📝 Restoring SSH keys..."
# Retrieve SSH private key
ssh_private=$(get_notes "SSH private key")
if [ -n "$ssh_private" ]; then
    echo "$ssh_private" > ~/.ssh/id_ed25519
    chmod 600 ~/.ssh/id_ed25519
    echo "  ✅ SSH private key restored"
else
    echo "  ⚠️  SSH private key not found in Bitwarden"
fi

# Retrieve SSH public key
ssh_public=$(get_notes "SSH public key")
if [ -n "$ssh_public" ]; then
    echo "$ssh_public" > ~/.ssh/id_ed25519.pub
    chmod 644 ~/.ssh/id_ed25519.pub
    echo "  ✅ SSH public key restored"
else
    echo "  ⚠️  SSH public key not found in Bitwarden"
fi

echo "📝 Restoring environment secrets..."
# Retrieve all secrets from Bitwarden
GITHUB_TOKEN=$(get_password "GitHub Token")

# Write ~/.secrets file
cat > ~/.secrets << EOF
# This file is auto-generated by setup_secrets.sh
# DO NOT commit this file to Git

# GitHub Token
export GITHUB_TOKEN="${GITHUB_TOKEN}"

chmod 600 ~/.secrets
echo "  ✅ Environment secrets restored to ~/.secrets"
EOF

# Retrieve AWS config
aws_config=$(get_notes "AWS config")
if [ -n "$aws_config" ]; then
    echo "$aws_config" > ~/.aws/config
    chmod 600 ~/.aws/config
    echo "  ✅ AWS config restored"
else
    echo "  ⚠️  AWS config not found in Bitwarden"
fi

echo ""
echo "✅ Secrets restored successfully!"
echo ""
echo "⚠️  Important reminders:"
echo "  - Never commit ~/.secrets, ~/.ssh/id_ed25519, or ~/.aws/* to Git"
echo "  - Add these to your global .gitignore if not already present"
echo "  - Re-run this script after updating secrets in Bitwarden"
echo ""
echo "📋 Summary:"
echo "  SSH keys: ~/.ssh/id_ed25519, ~/.ssh/id_ed25519.pub"
echo "  Environment variables: ~/.secrets"
echo "  AWS credentials: ~/.aws/credentials, ~/.aws/config"
echo ""
echo "To load environment variables in your current shell:"
echo "  source ~/.secrets"
